name: Troy Ready
bio: 'Professional Geek'
picture: 'assets/images/profile.jpg'

url: http://troyready.com
permalink: /:title/

analytics: 'UA-MYANALYTICS'
disqus: troyready
facebook: troyready
twitter: troyready
googleplus: +TroyReady
instagram: 
linkedin: in/troyready
youtube: user/troyready
github: troyready
email: myfirstname@myfirstnamemylastname.com

exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor]

gems:
  - jemoji
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: http://troyready.com
